name: elhaga
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_map: ^1.1.1
  flutter_secure_storage: ^8.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.2
  location: ^4.4.0
  page_transition: ^2.0.9
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSansArabic_Condensed-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
